/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package markus.taller;

import javax.swing.JOptionPane;

/**
 *
 * @author johan
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    private int a = 0, a1 = 10000, a2 = 5000, a3 = 3000, perro, tamaño, horas, guardar, guardar1;

    public interfaz() {
        initComponents();
        Ltamaño.setVisible(false);
        Jtamaño.setVisible(false);
        Lhoras.setVisible(false);
        Jhoras.setVisible(false);
        Bsiguiente.setVisible(false);
        Ltotal.setVisible(false);
        Jtotal.setVisible(false);
        Bcalcular.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jperros = new javax.swing.JTextField();
        Lperros = new javax.swing.JLabel();
        Jtamaño = new javax.swing.JComboBox<>();
        Ltamaño = new javax.swing.JLabel();
        Lhoras = new javax.swing.JLabel();
        Jhoras = new javax.swing.JTextField();
        Bcalcular = new javax.swing.JButton();
        Jtotal = new javax.swing.JTextField();
        Ltotal = new javax.swing.JLabel();
        Bingresar = new javax.swing.JButton();
        Bsiguiente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jperros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JperrosActionPerformed(evt);
            }
        });
        getContentPane().add(Jperros, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 90, -1));

        Lperros.setText("Cantidad de perros");
        getContentPane().add(Lperros, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        Jtamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige", "Grande", "Mediano", "Pequeño" }));
        Jtamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtamañoActionPerformed(evt);
            }
        });
        getContentPane().add(Jtamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 90, -1));

        Ltamaño.setText("¿Que tamaño tiene?");
        getContentPane().add(Ltamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        Lhoras.setText("¿Cuentas horas de paseo para ese perro?");
        getContentPane().add(Lhoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        getContentPane().add(Jhoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 90, -1));

        Bcalcular.setText("Calcular");
        Bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcalcularActionPerformed(evt);
            }
        });
        getContentPane().add(Bcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        Jtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtotalActionPerformed(evt);
            }
        });
        getContentPane().add(Jtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 80, -1));

        Ltotal.setText("Total a pagar");
        getContentPane().add(Ltotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        Bingresar.setText("Ingresar");
        Bingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BingresarActionPerformed(evt);
            }
        });
        getContentPane().add(Bingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        Bsiguiente.setText("Siguiente");
        Bsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(Bsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JperrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JperrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JperrosActionPerformed

    private void JtamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtamañoActionPerformed

    private void JtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtotalActionPerformed

    private void BingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BingresarActionPerformed
        Lperros.setVisible(false);
        Jperros.setVisible(false);
        Bingresar.setVisible(false);
        this.perro = Integer.parseInt(Jperros.getText());
        if (this.perro >= 1) {
            Ltamaño.setVisible(true);
            Jtamaño.setVisible(true);
            Lhoras.setVisible(true);
            Jhoras.setVisible(true);
            Bsiguiente.setVisible(true);
        } 

        //JOptionPane.showMessageDialog(this, "mira:"+a);
    }//GEN-LAST:event_BingresarActionPerformed

    private void BcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcalcularActionPerformed

        Ltotal.setVisible(true);
        Jtotal.setVisible(true);
        Bcalcular.setVisible(false);
        if (this.perro > 1) {
            this.guardar = this.guardar1 / 100;
            this.guardar = this.guardar * 10;
            this.guardar = this.guardar1 - this.guardar;
        }
        Jtotal.setText(Integer.toString(this.guardar));
    }//GEN-LAST:event_BcalcularActionPerformed

    private void BsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsiguienteActionPerformed
        
        
        if (this.perro > this.a) {
            this.tamaño = Jtamaño.getSelectedIndex();
            this.horas = Integer.parseInt(Jhoras.getText());
            if (this.tamaño == 1) {
                this.guardar = this.a1 * this.horas;
                this.guardar1 = this.guardar + this.guardar1;
            } else if (this.tamaño == 2) {
                this.guardar = this.a2 * this.horas;
                this.guardar1 = this.guardar + this.guardar1;
            } else if (this.tamaño == 3) {
                this.guardar = this.a3 * this.horas;
                this.guardar1 = this.guardar + this.guardar1;
            } else {
                JOptionPane.showConfirmDialog(this, "Elige un tamaño:");
            }
            this.a = this.a + 1;
            Jhoras.setText(null);
            Jtamaño.setSelectedIndex(0);
        } 
        if (this.perro == this.a) {
            Ltamaño.setVisible(false);
            Jtamaño.setVisible(false);
            Lhoras.setVisible(false);
            Jhoras.setVisible(false);
            Bcalcular.setVisible(true);
            Bsiguiente.setVisible(false);
        }
    }//GEN-LAST:event_BsiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcalcular;
    private javax.swing.JButton Bingresar;
    private javax.swing.JButton Bsiguiente;
    private javax.swing.JTextField Jhoras;
    private javax.swing.JTextField Jperros;
    private javax.swing.JComboBox<String> Jtamaño;
    private javax.swing.JTextField Jtotal;
    private javax.swing.JLabel Lhoras;
    private javax.swing.JLabel Lperros;
    private javax.swing.JLabel Ltamaño;
    private javax.swing.JLabel Ltotal;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
